services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    depends_on:
      - db
#    volumes:
#      - ./backend:/var/www/html
#      - ./backend/vendor:/var/www/html/vendor
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "4200:4200"
#    volumes:
#      - ./frontend:/usr/src/app
#      - node_modules_data:/usr/src/app/node_modules
    working_dir: /usr/src/app
#    tty: true
    command: npm start

volumes:
  db_data:
#  vendor_data:
#  node_modules_data:
